language: cpp
matrix:
  include:
  - os: linux
    dist: xenial
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install devscripts build-essential lintian dh-make
    - sudo apt-get install libssl-dev autoconf
    compiler:
    - gcc
    script:
    - echo $TRAVIS_TAG
    - make
    after_script:
     addons:
     artifacts: true
before_install:
    - eval "${MATRIX_EVAL}"




